In [9]:
import numpy as np
number = np.array([10,20,30,40,50,123,25,100,30,154])
print(number +5)

[ 15  25  35  45  55 128  30 105  35 159]


In [10]:
print( number *2)

[ 20  40  60  80 100 246  50 200  60 308]


In [11]:
print( number/2)

[ 5.  10.  15.  20.  25.  61.5 12.5 50.  15.  77. ]


In [12]:
print(type(number))

<class 'numpy.ndarray'>


In [13]:
print(number +20)

[ 30  40  50  60  70 143  45 120  50 174]


In [21]:
print(number[0])
print(number[2])
print(number[-1])
print(number[1:4])
print(number[ :3])
print(np.mean(number))
print(np.sum(number))
print(np.max(number))
print(np.min(number))
print(np.zeros(5))
print(np.ones(5))
print(np.arange(1,11))
print(number.reshape(2,5))
print(number>20)
print(number.reshape(5,2))

10
30
154
[20 30 40]
[10 20 30]
58.2
582
154
10
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 10  20  30  40  50]
 [123  25 100  30 154]]
[False False  True  True  True  True  True  True  True  True]
[[ 10  20]
 [ 30  40]
 [ 50 123]
 [ 25 100]
 [ 30 154]]
